/**
 * Automatically translated from Java to Java
 * 
 * Original file: src/main/java/com/example/library/NotificationService.java
 * Module: NotificationService
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.service;

import com.converted.app.model.User;
import com.converted.app.model.Book;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

@Service
public class NotificationService {

    private static final Logger log = LoggerFactory.getLogger(NotificationService.class);

    public void sendEmail(String email, String subject, String message) {
        log.info("Sending email to: {}", email);
        log.info("Subject: {}", subject);
        log.info("Message: {}", message);
    }

    public void sendBorrowNotification(User user, Book book) {
        sendEmail(user.getEmail(),
                "Book Borrowed",
                "You have borrowed: " + book.getTitle());
    }

    public void sendReturnNotification(User user, Book book) {
        sendEmail(user.getEmail(),
                "Book Returned",
                "You have returned: " + book.getTitle());
    }
}