/**
 * Automatically translated from Java to Java
 * 
 * Original file: src/main/java/com/example/library/LibraryApplication.java
 * Module: LibraryApplication
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp;

import com.converted.app.model.Book;
import com.converted.app.model.User;
import com.converted.app.service.LibraryService;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;

@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        ConfigurableApplicationContext context = SpringApplication.run(LibraryApplication.class, args);

        LibraryService libraryService = context.getBean(LibraryService.class);

        // Add some books
        Book book1 = new Book("978-0-123", "Java Programming", "John Doe", 2020);
        Book book2 = new Book("978-0-456", "Spring Boot Guide", "Jane Smith", 2021);

        libraryService.addBook(book1);
        libraryService.addBook(book2);

        // Register users
        User user1 = new User("U001", "Alice", "alice@example.com");
        User user2 = new User("U002", "Bob", "bob@example.com");

        libraryService.registerUser(user1);
        libraryService.registerUser(user2);

        // Borrow a book
        boolean borrowed = libraryService.borrowBook("U001", "978-0-123");
        System.out.println("Borrow successful: " + borrowed);

        // Display stats
        libraryService.displayStats();
    }
}