/**
 * Automatically translated from Java to Java
 * 
 * Original file: src/main/java/com/example/library/DateUtils.java
 * Module: DateUtils
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.utils;

import org.springframework.stereotype.Component;

import java.util.Date;
import java.text.SimpleDateFormat;

@Component
public class DateUtils {
    private static final SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
    
    public String formatDate(Date date) {
        return formatter.format(date);
    }
    
    public Date getCurrentDate() {
        return new Date();
    }
    
    public long daysBetween(Date start, Date end) {
        long diff = end.getTime() - start.getTime();
        return diff / (1000 * 60 * 60 * 24);
    }
}