/**
 * Automatically translated from Java to Java
 * 
 * Original file: src/main/java/com/example/library/ValidationUtils.java
 * Module: ValidationUtils
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.utils;

import java.util.regex.Pattern;

public class ValidationUtils {
    
    public static boolean isValidISBN(String isbn) {
        if (isbn == null) return false;
        String cleaned = isbn.replaceAll("-", "");
        return cleaned.length() == 10 || cleaned.length() == 13;
    }
    
    public static boolean isValidEmail(String email) {
        if (email == null) return false;
        String emailRegex = "^[A-Za-z0-9+_.-]+@(.+)$";
        Pattern pattern = Pattern.compile(emailRegex);
        return pattern.matcher(email).matches();
    }
    
    public static String sanitize(String input) {
        if (input == null) return "";
        return input.trim();
    }
}