/**
 * Automatically translated from Java to Java
 * 
 * Original file: src/main/java/com/example/library/Library.java
 * Module: Library
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.model;

import java.util.HashMap;
import java.util.Map;

public class Library {
    private String libraryName;
    private Map<String, Book> books;
    private Map<String, User> users;
    private Integer totalBorrowed;
    
    public Library(String name) {
        this.libraryName = name;
        this.books = new HashMap<>();
        this.users = new HashMap<>();
        this.totalBorrowed = 0;
    }
    
    public boolean addBook(Book book) {
        if (books.containsKey(book.getIsbn())) {
            return false;
        }
        books.put(book.getIsbn(), book);
        return true;
    }
    
    public boolean registerUser(User user) {
        if (users.containsKey(user.getUserId())) {
            return false;
        }
        users.put(user.getUserId(), user);
        return true;
    }
    
    public boolean borrowBook(String userId, String isbn) {
        User user = users.get(userId);
        Book book = books.get(isbn);
        
        if (user == null || book == null) {
            return false;
        }
        
        if (!book.isAvailable() || !user.canBorrowMore()) {
            return false;
        }
        
        book.setAvailable(false);
        user.borrowBook(isbn);
        totalBorrowed++;
        return true;
    }
    
    public boolean returnBook(String userId, String isbn) {
        User user = users.get(userId);
        Book book = books.get(isbn);
        
        if (user == null || book == null) {
            return false;
        }
        
        book.setAvailable(true);
        user.returnBook(isbn);
        totalBorrowed--;
        return true;
    }
    
    public void displayStats() {
        System.out.println("Library: " + libraryName);
        System.out.println("Total books: " + books.size());
        System.out.println("Total users: " + users.size());
        System.out.println("Books borrowed: " + totalBorrowed);
    }
}