/**
 * Automatically translated from Java to Java
 * 
 * Original file: src/main/java/com/example/library/LibraryManager.java
 * Module: LibraryManager
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.model;

import com.converted.app.model.Library;
import com.converted.app.model.Book;
import com.converted.app.model.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class LibraryManagerService {

    private final Library library;
    private final BookService bookService;
    private final UserService userService;
    private final NotificationService notificationService;

    @Autowired
    public LibraryManagerService(Library library, BookService bookService, UserService userService, NotificationService notificationService) {
        this.library = library;
        this.bookService = bookService;
        this.userService = userService;
        this.notificationService = notificationService;
    }

    public boolean processBorrow(String userId, String isbn) {
        User user = userService.findUser(userId);
        Book book = bookService.findBook(isbn);
        boolean success = library.borrowBook(user, book);
        if (success) {
            notificationService.sendBorrowNotification(user, book);
        }
        return success;
    }

    public boolean processReturn(String userId, String isbn) {
        User user = userService.findUser(userId);
        Book book = bookService.findBook(isbn);
        boolean success = library.returnBook(user, book);
        if (success) {
            notificationService.sendReturnNotification(user, book);
        }
        return success;
    }
}