/**
 * Automatically translated from Java to Java
 * 
 * Original file: src/main/java/com/example/library/UserRepository.java
 * Module: UserRepository
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.model;

import com.converted.app.model.User;
import org.springframework.stereotype.Repository;
import java.util.List;
import java.util.ArrayList;
import java.util.Optional;

@Repository
public class UserRepository {
    private List<User> users = new ArrayList<>();
    
    public void save(User user) {
        users.add(user);
    }
    
    public Optional<User> findById(String userId) {
        for (User user : users) {
            if (user.getUserId().equals(userId)) {
                return Optional.of(user);
            }
        }
        return Optional.empty();
    }
    
    public List<User> findAll() {
        return new ArrayList<>(users);
    }
    
    public void delete(String userId) {
        users.removeIf(user -> user.getUserId().equals(userId));
    }
}