/**
 * Automatically translated from Java to Java
 * 
 * Original file: src/main/java/com/example/library/User.java
 * Module: User
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.model;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;
import java.util.ArrayList;
import java.util.List;

public class User {
    @NotBlank(message = "User ID is mandatory")
    private String userId;

    @NotBlank(message = "Name is mandatory")
    private String name;

    @NotBlank(message = "Email is mandatory")
    @Email(message = "Email should be valid")
    private String email;

    private List<String> borrowedBooks;
    private final int maxBooksAllowed = 5;

    public User(@NotBlank(message = "User ID is mandatory") String userId, 
                @NotBlank(message = "Name is mandatory") String name, 
                @NotBlank(message = "Email is mandatory") @Email(message = "Email should be valid") String email) {
        this.userId = userId;
        this.name = name;
        this.email = email;
        this.borrowedBooks = new ArrayList<>();
    }

    public String getUserId() { return userId; }
    public String getName() { return name; }
    public String getEmail() { return email; }

    public boolean canBorrowMore() {
        return borrowedBooks.size() < maxBooksAllowed;
    }

    public boolean borrowBook(@NotBlank(message = "ISBN is mandatory") String isbn) {
        if (canBorrowMore() && !borrowedBooks.contains(isbn)) {
            borrowedBooks.add(isbn);
            return true;
        }
        return false;
    }

    public boolean returnBook(@NotBlank(message = "ISBN is mandatory") String isbn) {
        return borrowedBooks.remove(isbn);
    }

    public void displayInfo() {
        System.out.println("User ID: " + userId);
        System.out.println("Name: " + name);
        System.out.println("Email: " + email);
        System.out.println("Borrowed books: " + borrowedBooks.size() + "/" + maxBooksAllowed);
    }
}